# Generated by Django 4.2.30 on 2026-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
